[workspace]
members = [
  "cli",
  "host",
  "polis",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.65"
wasmi = "0.8.0"

[workspace.dependencies.clap]
version = "4.0.8"
features = [
  "derive"
]
