[package]
name = "metropoli-polis"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
wasmi.workspace = true

[dev-dependencies]
wabt.workspace = true
